---
# tasks file for ec2-prov
 - name: Launch new EC2 Instance
   ec2:
     key_name: "{{ keypair }}"
     group_id: sg-096797fc3ce901c63
     instance_type: "{{ instance_type}}"
     image: "{{ image }}"
     vpc_subnet_id: subnet-0e3dde91a0167bb9c
     region: "{{ region }}"
     instance_tags: '{"Name":"{{Machine_Name}}","Environment":"Test_POC"}'
     assign_public_ip: yes
     wait: true
     count: "{{count}}"
     ec2_url: "{{ ec_url }}"
     aws_access_key: "{{ aws_ac_key }}"
     aws_secret_key: "{{ aws_sec_key }}"
     volumes:
       - device_name: /dev/sda1
         volume_size: "{{ ec2_volume_size }}"
         delete_on_termination: true
   register: ec2

 - debug: var=item
   with_items: ec2.instances

 - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
   local_action: lineinfile
                 dest="/opt/ansible/envpov/inventory/hosts"
                 regexp={{ item.public_ip }}
                 insertafter="[app_server]" line={{ item.public_ip }}
   with_items: ec2.instances



